# Generated by Django 3.2.9 on 2021-12-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211203_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlink',
            options={'verbose_name': 'ссылка проекта', 'verbose_name_plural': 'ссылки проектов'},
        ),
    ]
