# Generated by Django 3.2.9 on 2021-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_info',
            field=models.TextField(blank=True, verbose_name='информация при правильном ответе'),
        ),
        migrations.AddField(
            model_name='question',
            name='incorrect_info',
            field=models.TextField(blank=True, verbose_name='информация при неправильном ответе'),
        ),
    ]
