# Generated by Django 3.2.9 on 2021-12-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20211203_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='порядок'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating_change',
            field=models.SmallIntegerField(default=5, verbose_name='рейтинг за вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.quizz', verbose_name='викторина'),
        ),
    ]
