# Generated by Django 3.2.9 on 2021-12-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectlink_options'),
        ('testing', '0003_auto_20211203_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='projects.project', verbose_name='проект'),
        ),
    ]
