name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    name: deploy on prod
    steps:
      - name: deploy production with ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/psb-case-back
            git pull
            cd ~/psb-case-back/PSB-case-2021
            git pull
            cd ..
            docker-compose -f production.yml exec -T postgres backup
            docker-compose -f production.yml up --detach --build --force-recreate
